export const CREATE_TOURNAMENT_TRANSACTION = 'CREATE_TOURNAMENT_TRANSACTION';
export const CREATE_TOPUP_TRANSACTION = 'CREATE_TOPUP_TRANSACTION';
export const PARTICIPATE_TOURNAMENT = 'PARTICIPATE_TOURNAMENT';
